import "@shopify/shopify-app-react-router/adapters/node";
import {
  ApiVersion,
  AppDistribution,
  shopifyApp,
  BillingInterval,
} from "@shopify/shopify-app-react-router/server";
import { PrismaSessionStorage } from "@shopify/shopify-app-session-storage-prisma";
import prisma from "./db.server";

export const PLAN_STARTER = 'Starter (Commission)';
export const PLAN_GROWTH = 'Growth (Hybrid)';
export const PLAN_SCALE = 'Scale (Flat)';

export const BILLING_CONFIG = {
  [PLAN_STARTER]: {
    amount: 0.0,
    currencyCode: 'USD',
    interval: BillingInterval.Every30Days,
    usageTerms: "4% commission on sales generated by negotiated offers.",
    cappedAmount: 1000.0,
  },
  [PLAN_GROWTH]: {
    amount: 19.0,
    currencyCode: 'USD',
    interval: BillingInterval.Every30Days,
    usageTerms: "1% commission on sales generated by negotiated offers.",
    cappedAmount: 1000.0,
  },
  [PLAN_SCALE]: {
    amount: 59.0,
    currencyCode: 'USD',
    interval: BillingInterval.Every30Days,
  }
};

const shopify = shopifyApp({
  apiKey: process.env.SHOPIFY_API_KEY,
  apiSecretKey: process.env.SHOPIFY_API_SECRET || "",
  apiVersion: ApiVersion.October24,
  scopes: process.env.SCOPES?.split(","),
  appUrl: process.env.SHOPIFY_APP_URL || "",
  authPathPrefix: "/auth",
  sessionStorage: new PrismaSessionStorage(prisma),
  distribution: AppDistribution.AppStore,
  billing: BILLING_CONFIG,
  ...(process.env.SHOP_CUSTOM_DOMAIN
    ? { customShopDomains: [process.env.SHOP_CUSTOM_DOMAIN] }
    : {}),
});

export default shopify;
export const apiVersion = ApiVersion.October24;
export const addDocumentResponseHeaders = shopify.addDocumentResponseHeaders;
export const authenticate = shopify.authenticate;
export const unauthenticated = shopify.unauthenticated;
export const login = shopify.login;
export const registerWebhooks = shopify.registerWebhooks;
export const sessionStorage = shopify.sessionStorage;
